#!/bin/sh
case $1 in
	start)
		if [ ! -f pirb.pid ]; then
			./pirb.py >> /dev/null &
			pid=$!
			echo $pid > pirb.pid
			echo "PIRB started into background (PID: $pid)"
		else
			echo "PIRB is already running"
		fi
		;;
	stop)
		if [ -f pirb.pid ]; then
			pid=$(cat pirb.pid)
			kill -9 $pid
			rm -f pirb.pid
			echo "PIRB is stopped (PID: $pid)"
		else
			echo "PIRB is not running"
		fi
		;;
	restart)
		if [ -f pirb.pid ]; then
			./pirb stop
			./pirb start
		else
			./pirb start
		fi
		;;
	force-start)
		rm -f pirb.pid
		./pirb start
		;;
	debug)
		while [ 1 ]; do
			./pirb.py
		done
		;;
	*)
		echo "start | stop | restart | force-start | debug"
		;;
esac

