#!/bin/sh
case $1 in
	start)
		if [ ! -f pirb.pid ]; then
			python pirb.py >> /dev/null &
			pid=$!
			echo $pid > pirb.pid
			echo "PIRB started into background (PID: $pid)"
		else
			pid=$(cat pirb.pid)
			status=false
			for data in $(ps | grep $pid); do
				status=true
			done
			if [ $status == false ]; then
				sh pirb start
			else
				echo "PIRB is already running"
			fi
		fi
		;;
	stop)
		if [ -f pirb.pid ]; then
			pid=$(cat pirb.pid)
			kill -9 $pid
			rm -f pirb.pid
			echo "PIRB is stopped (PID: $pid)"
		else
			echo "PIRB is not running"
		fi
		;;
	restart)
		if [ -f pirb.pid ]; then
			sh pirb stop
			sh pirb start
		else
			sh pirb start
		fi
		;;
	debug)
		while [ 1 ]; do
			python pirb.py
		done
		;;
	status)
		if [ -f pirb.pid ]; then
			pid=$(cat pirb.pid)
			status="PIRB seems to be crashed"
			for data in $(ps | grep $pid); do
				status="PIRB is running"
			done
		else
			status="PIRB is not running"
		fi
		echo $status
		;;
	*)
		echo "start | stop | restart | debug | status"
		;;
esac

